/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author patri
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setExtendedState(MAXIMIZED_BOTH);
    }

    private void cargarOpcionesMenu() {
        if (negocio.Variables.rolNombre.equals("Administrador")) {

        } else if (negocio.Variables.rolNombre.equals("Produccion")) {

        } else if (negocio.Variables.rolNombre.equals("Filtracion")) {

        } else if (negocio.Variables.rolNombre.equals("Camara")) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.setColor(Color.white);
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        menuBar = new javax.swing.JMenuBar();
        mnuBodega = new javax.swing.JMenu();
        mnuDepositos = new javax.swing.JMenu();
        menuCategoria = new javax.swing.JMenuItem();
        menuDepositos = new javax.swing.JMenuItem();
        mnuMovimientos = new javax.swing.JMenu();
        menuEntradas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuRol = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenuItem();
        menuEntrada = new javax.swing.JMenu();
        menuElaboracion = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control Stock Bodega");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1215, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        mnuBodega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logosoftware.png"))); // NOI18N
        mnuBodega.setText("Bodega");
        menuBar.add(mnuBodega);

        mnuDepositos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cilindro1.png"))); // NOI18N
        mnuDepositos.setText("Depositos");

        menuCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuCategoria.setText("Referencias");
        menuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriaActionPerformed(evt);
            }
        });
        mnuDepositos.add(menuCategoria);

        menuDepositos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuDepositos.setText("Depósitos");
        menuDepositos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDepositosActionPerformed(evt);
            }
        });
        mnuDepositos.add(menuDepositos);

        menuBar.add(mnuDepositos);

        mnuMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/movimiento.png"))); // NOI18N
        mnuMovimientos.setText("Movimientos");

        menuEntradas.setText("Entradas");
        menuEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntradasActionPerformed(evt);
            }
        });
        mnuMovimientos.add(menuEntradas);

        menuBar.add(mnuMovimientos);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/acceso.png"))); // NOI18N
        jMenu3.setText("Acceso");

        menuRol.setText("Rol");
        menuRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRolActionPerformed(evt);
            }
        });
        jMenu3.add(menuRol);

        menuUsuarios.setText("Usuarios");
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });
        jMenu3.add(menuUsuarios);

        menuBar.add(jMenu3);

        menuEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trabajadores.png"))); // NOI18N
        menuEntrada.setText("Personal");

        menuElaboracion.setText("Produccion");
        menuElaboracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuElaboracionActionPerformed(evt);
            }
        });
        menuEntrada.add(menuElaboracion);

        menuClientes.setText("Dirección");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        menuEntrada.add(menuClientes);

        menuBar.add(menuEntrada);

        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuBar.add(menuSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDepositosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDepositosActionPerformed
        FrmDeposito frm = new FrmDeposito();
        escritorio.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_menuDepositosActionPerformed

    private void menuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriaActionPerformed
        FrmReferencia frm = new FrmReferencia();
        escritorio.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_menuCategoriaActionPerformed

    private void menuRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRolActionPerformed
        FrmRol frm = new FrmRol();
        escritorio.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_menuRolActionPerformed

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
        FrmUsuario frm = new FrmUsuario();
        escritorio.add(frm);
        frm.setVisible(true);

    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void menuElaboracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuElaboracionActionPerformed
        FrmTrabajadorProduccion frm = new FrmTrabajadorProduccion();
        escritorio.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_menuElaboracionActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        FrmTrabajadoresDireccion frm = new FrmTrabajadoresDireccion();
        escritorio.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuSalirMouseClicked

    private void menuEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntradasActionPerformed
        FrmIngreso frm = new FrmIngreso(this);
        escritorio.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_menuEntradasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuCategoria;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuDepositos;
    private javax.swing.JMenuItem menuElaboracion;
    private javax.swing.JMenu menuEntrada;
    private javax.swing.JMenuItem menuEntradas;
    private javax.swing.JMenuItem menuRol;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenuItem menuUsuarios;
    private javax.swing.JMenu mnuBodega;
    private javax.swing.JMenu mnuDepositos;
    private javax.swing.JMenu mnuMovimientos;
    // End of variables declaration//GEN-END:variables

}
